### ISSUE TITLE
Dúvida sobre a página

### ISSUE THREAD

**Issue by H4x0rModdz** [JoiaribeAlves/rescue#11]
Vocês realmente precisam colocar a parte "páginas" no footer sendo que ela já está explicita no começo do website? É uma dúvida sincera, já que acredito que essa parte não será usada e apenas irá usar memória do servidor sem motivos, sabe? Estou jogando um PR onde retiro a área páginas, coloco centralizada e também estou testando para ver se acho algum tipo de vulnerabilidade no sistema.
![image](https://github.com/JoiaribeAlves/rescue/assets/63929563/263e3963-c0f5-4c0a-8ee6-9dc5a3251b3d)

**Comment by JoiaribeAlves** [comment]
Boa noite lucas. Agradeço a sua obsevação. Realmente isso é desnecessário. Está aí desde o começo, pois o layout do menu estava uma bagunça, depois arganizamos o menu e o footer acabou permanecendo como estava.

**Comment by H4x0rModdz** [comment]
Boa tarde, irmão. Primeiramente, obrigado por responder à minha issue. Eu pensei que talvez seria por isso, mas mesmo assim quis confirmar para saber. Não sou ligado ao front-end, mas conheci o projeto através de umas pesquisas sobre projetos que estejam servindo de ajuda para o RS e então resolvi dar uma "fuchicada" por eles, kkkkk. Bom, acredito também que possam olhar para um limite de solicitações de resgate pelo mesmo usuário (para que não hajam negações de serviço devido a quantidade de request) e também um envio da solicitação direto para uma área que pessoas autorizadas (ou por automação) possa verificar a credibilidade das informações recebidas (sejam elas por nome, local, entre outras). No mais, adorei o projeto, uma pena eu não conhecer tanto sobre typescript.

**Comment by JoiaribeAlves** [comment]
Pois é, tem muito espaço pra melhorias. Tudo isso aí foi criado em uma semana kkk, foi bem corrido. É natural ter "várias coisas estranhas" mesmo. Anotei suas sugestões, agradeço bastante. Em relação a não ter autenticação/autorização (ainda), e por isso, qualquer pessoa poder modificar os dados é por que inicialmente queríamos algo que fosse bem direto ao ponto, sem "burocrácias".

Tem um pessoal com um projeto bem legal também, não sei se você já conhece, vou colocar o link aqui, caso queira da uma olhadinha, porém lá também é full typescript kkk. Mas, é um projeto bem mais robusto, acredito que lá você terá mais chance de ajudar.

[SOS-RS](https://github.com/sos-rs)

**Comment by H4x0rModdz** [comment]
Kkkkk, eu msm não tinha visto que o projeto era de uma semana, achei que já tinha um tempo e só estavam sem auth ainda daí resolvi falar sobre. Sobre o SOS-Rs, gostei do projeto, vou dar uma olhada a mais por dentro dele e, caso eu perceba algo, contribuo lá. Fico triste apenas por não ser projetos .NET em que eu tenho maior engajamento para participar 😢. Obrigado por compartilhar o projeto. Tmj, irmão!

**Comment by JoiaribeAlves** [comment]
Eu que agradeço irmão. Tmj. Quem sabe da próxima né!? Vlw
